Update smartyourfood.oc_food_tag set tag_name_en = 'All' where tag_id = 0  ;
Update smartyourfood.oc_food_tag set tag_name_en = 'cold dish' where tag_id = 1  ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Casserole' where tag_id = 2  ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Served 24 Hours' where tag_id = 3  ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Breakfast (6:00am-11:00am)' where tag_id = 4  ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Dessert' where tag_id = 5  ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Drinks & Bubble Tea' where tag_id = 6  ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Soup & Garlic Bread' where tag_id = 7  ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Entrees' where tag_id = 8  ;
Update smartyourfood.oc_food_tag set tag_name_en = 'A la Carte' where tag_id = 9  ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Burgers & Sandwiches' where tag_id = 10 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Grill' where tag_id = 11 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Side Dishes' where tag_id = 12 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Main Course' where tag_id = 13 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Yee Mein' where tag_id = 14 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Clay pot' where tag_id = 15 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Chow Mein & Rice Noodle' where tag_id = 16 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Rice in Soup' where tag_id = 17 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Curry Rice Dishes' where tag_id = 18 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'BBQ Meat' where tag_id = 19 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Fried Rice' where tag_id = 20 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Rice' where tag_id = 21 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Northern Pastry' where tag_id = 22 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Soup' where tag_id = 23 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Hot Fries' where tag_id = 24 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Noodle with soup on side' where tag_id = 25 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Noodle in Soup' where tag_id = 26 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Congee' where tag_id = 27 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Pan Fried Food' where tag_id = 28 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Chicken & Duck' where tag_id = 29 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Beef & Lamb' where tag_id = 30 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Pork' where tag_id = 31 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Stew' where tag_id = 32 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Vegetarian' where tag_id = 33 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Staple food' where tag_id = 34 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'BBQ ' where tag_id = 35 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Beverage' where tag_id = 36 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Braised Food' where tag_id = 37 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Sweet Chicken' where tag_id = 38 ;
Update smartyourfood.oc_food_tag set tag_name_en = 'Seafood' where tag_id = 39 ;