UPDATE `smartyourfood`.`oc_setting` SET `value`='5' WHERE `setting_id`='328';
UPDATE `smartyourfood`.`oc_setting` SET `value`='8' WHERE `setting_id`='329';
UPDATE `smartyourfood`.`oc_setting` SET `value`='14' WHERE `setting_id`='330';
UPDATE `smartyourfood`.`oc_setting` SET `value`='10' WHERE `setting_id`='331';
UPDATE `smartyourfood`.`oc_setting` SET `value`='1' WHERE `setting_id`='332';
UPDATE `smartyourfood`.`oc_setting` SET `value`='15' WHERE `setting_id`='333';
UPDATE `smartyourfood`.`oc_setting` SET `value`='11' WHERE `setting_id`='334';
UPDATE `smartyourfood`.`oc_setting` SET `value`='12' WHERE `setting_id`='335';
UPDATE `smartyourfood`.`oc_setting` SET `value`='16' WHERE `setting_id`='336';
